version: '3.8'
services:
  redis-node-1:
    image: redis:7-alpine
    container_name: redis-node-1
    ports:
      - "6379:6379"
    command: >
      redis-server --cluster-enabled yes --cluster-config-file nodes.conf
      --cluster-node-timeout 5000 --appendonly yes
      --cluster-announce-ip 127.0.0.1
      --cluster-announce-port 6379
      --cluster-announce-bus-port 16379

  redis-node-2:
    image: redis:7-alpine
    container_name: redis-node-2
    ports:
      - "6380:6379"
    command: >
      redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf
      --cluster-node-timeout 5000 --appendonly yes
      --cluster-announce-ip 127.0.0.1
      --cluster-announce-port 6380
      --cluster-announce-bus-port 16380

  redis-node-3:
    image: redis:7-alpine
    container_name: redis-node-3
    ports:
      - "6381:6379"
    command: >
      redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf
      --cluster-node-timeout 5000 --appendonly yes
      --cluster-announce-ip 127.0.0.1
      --cluster-announce-port 6381
      --cluster-announce-bus-port 16381

  redis-cluster-init:
    image: redis:7-alpine
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
    entrypoint: >
      sh -c "
        sleep 5 &&
        redis-cli --cluster create 127.0.0.1:6379 127.0.0.1:6380 127.0.0.1:6381 --cluster-replicas 0 --cluster-yes
      "
